---
title: "Rideograms of Bmori and Pinterpunctella synteny blocks"
output: html_notebook
author: "Hernan Lorenzi"
---

```{r}
library(circlize)
library(dplyr)
library(colortools)
```

### Load data
```{r}
chr2acc <- read.csv(file = "chr2acc.csv", header = 1)
karyotype_filter <- tibble(read.table("./karyotype.filter.txt", header = 1, sep = "\t", stringsAsFactors = F))
synteny_filter <- tibble(read.table("./Pinter_vs_Bmori_promer.matchList.filtered.synteny.txt", header = 1, sep = "\t", stringsAsFactors = F))

# Add chromosome names
karyotype_filter <- merge(karyotype_filter, chr2acc, by.x = "Chr", by.y = "Accession_ID", incomparables = 'chrna', all.x = TRUE)

# Replace NAs in chromosome names with chrna id.
karyotype_filter$Chromosome_ID[is.na(karyotype_filter$Chromosome_ID)] <- 'chrna'

# Add chr id "NW_026525664.1" to Pinter scfld NW_026525664.1
karyotype_filter$Chromosome_ID[karyotype_filter$Chr == "NW_026525664.1"] <- "NW_026525664.1"

# Create list of chr acc vs chr id
chrid.list <- karyotype_filter$Chromosome_ID
names(chrid.list) <- karyotype_filter$Chr

# Adjust chromosoma label distance to track
ymm <- rep(14, length(karyotype_filter$Chr))
names(ymm) <- karyotype_filter$Chr
ymm["NW_026525664.1"] <- 40

karyotype_filter <- filter(karyotype_filter, End > 500000 | Chromosome_ID == 'chrZ')

# Add strand of hits
synteny_filter <- synteny_filter %>% mutate( Strand_1 = End_1 - Start_1)
synteny_filter <- synteny_filter %>% mutate( Strand_2 = End_2 - Start_2)
```

```{r}
set.seed(999)
n = 1000
df = data.frame(sectors = sample(letters[1:8], n, replace = TRUE),
    x = rnorm(n), y = runif(n))
```

```{r}
circos.par("track.height" = 0.1)
circos.initialize(sectors = df$sectors, x = df$x)

circos.track(df$sectors, y = df$y,
    panel.fun = function(x, y) {
        circos.text(CELL_META$xcenter, 
            CELL_META$cell.ylim[2] + mm_y(5), 
            CELL_META$sector.index)
        circos.axis(labels.cex = 0.6)
    }
)
col = rep(c("#FF0000", "#00FF00"), 4)
circos.trackPoints(df$sectors, df$x, df$y, col = col, pch = 16, cex = 0.5)
circos.text(-1, 0.5, "text", sector.index = "a", track.index = 1)

bgcol = rep(c("#EFEFEF", "#CCCCCC"), 4)
circos.trackHist(df$sectors, df$x, bin.size = 0.2, bg.col = bgcol, col = NA)

circos.track(df$sectors, x = df$x, y = df$y,
    panel.fun = function(x, y) {
        ind = sample(length(x), 10)
        x2 = x[ind]
        y2 = y[ind]
        od = order(x2)
        circos.lines(x2[od], y2[od])
})


circos.update(sector.index = "d", track.index = 2, 
    bg.col = "#FF8080", bg.border = "black")
circos.points(x = -2:2, y = rep(0.5, 5), col = "white")
circos.text(CELL_META$xcenter, CELL_META$ycenter, "updated", col = "white")

circos.track(ylim = c(0, 1), panel.fun = function(x, y) {
    xlim = CELL_META$xlim
    ylim = CELL_META$ylim
    breaks = seq(xlim[1], xlim[2], by = 0.1)
    n_breaks = length(breaks)
    circos.rect(breaks[-n_breaks], rep(ylim[1], n_breaks - 1),
                breaks[-1], rep(ylim[2], n_breaks - 1),
                col = rand_color(n_breaks), border = NA)
})


circos.link("a", 0, "b", 0, h = 0.4)
circos.link("c", c(-0.5, 0.5), "d", c(-0.5,0.5), col = "red",
    border = "blue", h = 0.2)
circos.link("e", 0, "g", c(-1,1), col = "green", border = "black", lwd = 2, lty = 2)

circos.clear()
```

# Set pallete
```{r}
bmori_kar <- filter(karyotype_filter, species == "Bmori")
my_pallete <- list()
my_pallete <- wheel("darkblue", num = nrow(bmori_kar))
names(my_pallete) <- bmori_kar$Chr

# my_pallete_synt <- list()
# my_pallete_synt <- sample(wheel("darkblue", num = length(unique(synteny$group))))
# names(my_pallete_synt) <- (unique(synteny$group))

```

# Synteny
```{r}
kar.start <- karyotype_filter[,c("Chr","Start","fill","species","size","color")]
colnames(kar.start) <- c("Chr","x","fill","species","size","color")
kar.end  <-  karyotype_filter[,c("Chr","End","fill","species","size","color")]
colnames(kar.end) <- c("Chr","x","fill","species","size","color")
kar <- rbind(kar.start,kar.end)

kar$Chr <- as.factor(kar$Chr)

kar <- kar[order(kar$species, kar$size, decreasing = F),]

pdf(file = "circos_synteny_plot.pdf",width = 30, height = 25)
circos.par("track.height" = 0.05, cell.padding = c(0, 0, 0, 0))
circos.initialize(sectors = kar$Chr, x = kar$x)

# Add strand track
circos.trackPlotRegion(sectors = kar$Chr, x = kar$x, ylim = c(-8,8),
                       panel.fun = function(x,y){
                        circos.text(CELL_META$xcenter, facing = "clockwise", niceFacing = T, cex = 2,
                           CELL_META$cell.ylim[2] + mm_y(ymm[CELL_META$sector.index]),
                           chrid.list[CELL_META$sector.index])
                        circos.axis(#labels.cex = 0.9, 
                                    #labels.facing = "clockwise",
                                    #labels.niceFacing = T, 
                                    major.tick.length = mm_y(4) 
                                    )
                         }   
                      )

# Add chromosomes
circos.trackPlotRegion(sectors = kar$Chr, x = kar$x, ylim = c(0,1), 
             panel.fun = function(x,y){
               sp <- filter(kar, Chr == CELL_META$sector.index)[1,'species']
               circos.update(sector.index = CELL_META$sector.index, 
                             track.index = CELL_META$track.index, 
                             bg.col = ifelse(sp == "Bmori",
                                my_pallete[CELL_META$sector.index],
                                "#CCCCCC")
                             )
               # circos.text(CELL_META$xcenter, facing = "clockwise", niceFacing = T, cex = 2,
               #             CELL_META$cell.ylim[2] + mm_y(ymm[CELL_META$sector.index]),
               #             chrid.list[CELL_META$sector.index])
               # circos.axis(labels.cex = 0.9, labels.facing = "clockwise",labels.niceFacing = T, major.tick.length = mm_y(4) )
             }
)


# Add syntenic blocks
for (idx in 1:nrow(synteny_filter)){
  #idx=1
  # Syntenic block coords
  idx_1 <- synteny_filter[idx, "Species_1"]
  idx_2 <- synteny_filter[idx, "Species_2"]
  point_1 <-  synteny_filter[idx, c("Start_1","End_1")]
  point_2 <- synteny_filter[idx, c("Start_2","End_2")]
  color <- paste0("#",synteny_filter[idx, "fill"])
  
  # strand values
  strand_y = ifelse(as.numeric(synteny_filter[idx, "Strand_1"]) * as.numeric(synteny_filter[idx, "Strand_2"]) > 0, yes = 8, no = -8)
  
  
  # Next if chromosome was filtered out
  if (nrow(karyotype_filter[karyotype_filter$Chr == as.character(idx_1),]) == 1 &
      nrow(karyotype_filter[karyotype_filter$Chr == as.character(idx_2),]) == 1){

        circos.link(sector.index1 = idx_1, point1 = point_1, 
                    sector.index2 = idx_2, point2 = point_2, 
                    col = my_pallete[as.character(idx_1)])
    
        strand_color = my_pallete[as.character(idx_1)]
        #circos.update(sector.index = idx_2, track.index = 1)
        circos.rect(xleft = as.numeric(point_2[1]), ybottom = min(strand_y,0), 
                    xright = as.numeric(point_2[2]), ytop = max(strand_y,0), 
                    col = strand_color, border = NA, sector.index = idx_2, track.index = 1)
        circos.rect(xleft = as.numeric(point_1[1]), ybottom = min(strand_y,0), 
                    xright = as.numeric(point_1[2]), ytop = max(strand_y,0), 
                    col = "#CCCCCC", border = NA, sector.index = idx_1, track.index = 1)
        
  }
}

# for (idx in 1:nrow(kar)){
#   print(kar$Chr[idx])
#   print(kar$species[idx])
#   print(ifelse(kar$species[idx] == "Bmori", "green","red"))
#   circos.update(sector.index = kar$Chr[idx], track.index = 1, 
#                 bg.col = ifelse(kar$species[idx] == "Bmori", "green","red")
#                 )
# }

circos.clear()
dev.off()
```

```{r}
set.seed(999)
mat = matrix(sample(18, 18), 3, 6) 
rownames(mat) = paste0("S", 1:3)
colnames(mat) = paste0("E", 1:6)

grid.col = c(S1 = "red", S2 = "green", S3 = "blue",
    E1 = "grey", E2 = "grey", E3 = "grey", E4 = "grey", E5 = "grey", E6 = "grey")
par(mfrow = c(1, 2))
chordDiagram(mat, grid.col = grid.col)
title("Default")
chordDiagram(mat, grid.col = grid.col, scale = TRUE)
title("scale = TRUE")
```



